name: CI

# Dispara este workflow em push ou pull request para as branches main ou develop
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Faz checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Configura Python (use a mesma versão do seu requirements.txt)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Instala dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install flake8

      # 4) Roda lint com Flake8
      - name: Lint with flake8
        run: |
          flake8 backend/app

      # 5) Roda testes (supondo que você use pytest e tenha tests/ configurado)
      - name: Run tests
        working-directory: .
        run: |
          pytest --maxfail=1 --disable-warnings -q
